### ISSUE TITLE
Source Code not available

### ISSUE THREAD

**Issue by Awesomerly** [daraem/customSongs#1]
It's good to commit the source code and put the dll/pck in the releases so that people know that it's not going to delete System32 or whatever

**Comment by daraem** [comment]
Ill update it srry

**Comment by Awesomerly** [comment]
Thank you :D keep cooking

**Comment by Awesomerly** [comment]
Also if you want, you could join the webfishing modding discord :)

There are a lot of helpful people there.

**Comment by daraem** [comment]
yep I asked a lot there ^^. Do you think is okay now?

**Comment by Awesomerly** [comment]
Yes!!

**Comment by daraem** [comment]
srry for reopening but how did you find my mod btw?

**Comment by Awesomerly** [comment]
I think I saw it in that discord

**Comment by daraem** [comment]
ohh nice
